# Generated by Django 5.0.6 on 2025-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название заголовка",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание Заголовка",
                        null=True,
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        upload_to="blog_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "data_bd",
                    models.DateField(
                        blank=True,
                        help_text="укажите дату создания",
                        null=True,
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "data_refresh",
                    models.DateField(
                        blank=True,
                        help_text="укажите дату изменения",
                        null=True,
                        verbose_name="дата изменения",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="укажите количество просмотров товара",
                        null=True,
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "data_send",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
            ],
        ),
    ]
