# Generated by Django 5.0.6 on 2025-02-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание заголовка",
                null=True,
                verbose_name="Содержимое",
            ),
        ),
    ]
