# Generated by Django 5.0.6 on 2025-02-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="укажите количество просмотров товара",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
