# Generated by Django 4.2.2 on 2025-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_author_product_sign_publication_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=2, help_text="Укажите цену", verbose_name="Цена"
            ),
            preserve_default=False,
        ),
    ]
